backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Hero, name: image, widget: image}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: Title, name: title, widget: string}
          - {label: "Heading First Line", name: heading1, widget: string}
          - {label: "Heading Second Line", name: heading2, widget: string}
          - {label: "Info 1", name: info1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Info 2", name: info2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Info 3", name: info3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Info 4", name: info4, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Featured", name: featured, widget: object, fields: [{label: "Heading First Line", name: heading1, widget: string}, {label: "Heading Second Line", name: heading2, widget: string}]}
          - {label: "Featured Course 1", name: course1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Featured Course 2", name: course2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Featured Course 3", name: course3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Featured Course 4", name: course4, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "Featured View All Text", name: featuredViewAll, widget: string}
          - {label: "Featured Banner", name: featuredBanner, widget: object, fields: [{label: Image, name: image, widget: image}, {label: "Heading Line 1", name: heading1, widget: string}, {label: "Heading Line 2", name: heading2, widget: string}]}
          - {label: "Featured Footer", name: featuredFooter, widget: object, fields: [{label: "Heading Line 1", name: heading1, widget: string}, {label: "Heading Line 2", name: heading2, widget: string}]}
          - {label: "Featured Logos", name: featuredLogo, widget: list, fields:[{label: Image, name: image, widget: image}, {label: "Alt Text", name: alt, widget: string}]} 
          - {label: "Recent Posts", name: recentPosts, widget: object, fields: [{label: "Heading 1", name: heading1, widget: string}, {label: "Heading 2", name: heading2, widget: string}]}
          - {label: "Recent Calendar", name: recentCalendar, widget: object, fields: [{label: "Heading 1", name: heading1, widget: string}, {label: "Heading 2", name: heading2, widget: string}]}
          - {label: "Menu Logo", name: menuLogo, widget: object, fields: [{label: Image, name: image, widget: image},{label: "Alt", name: alt, widget: string}]}
          - {label: "Footer Logo", name: footerLogo, widget: object, fields: [{label: Image, name: image, widget: image},{label: "Alt", name: alt, widget: string}]}
          - {label: "Menu Column 1", name: footerColumn1, widget: list, fields:[{label: "Text", name: text, widget: string}, {label: "href", name: href, widget: string}, {label: "Children", name: children, widget: list, fields:[{label: "Text", name: text, widget: string}, {label: "href", name: href, widget: string}]}]} 
          - {label: "Menu Column 2", name: footerColumn2, widget: list, fields:[{label: "Text", name: text, widget: string}, {label: "href", name: href, widget: string}, {label: "Children", name: children, widget: list, fields:[{label: "Text", name: text, widget: string}, {label: "href", name: href, widget: string}]}]} 
          - {label: "Menu Social Heading", name: footerSocialHeading, widget: string}
          - {label: "Menu Social", name: footerSocial, widget: list, fields:[{label: "Text", name: text, widget: string}, {label: "href", name: href, widget: string}, {label: "Children", name: children, widget: list, fields:[{label: "Text", name: text, widget: string}, {label: "href", name: href, widget: string}]}]} 
  - name: "post"
    label: "Posts"
    folder: "src/pages/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "event"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "From", name: "from", widget: "datetime"}
      - {label: "To", name: "to", widget: "datetime"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}